In [18]:
import psycopg2
import sqlalchemy
import pandas as pd

PG_PASSWORD = "npg_ChWPQjJLe8d7"
PG_USER = "neondb_owner"
PG_HOST = "ep-curly-grass-a163zwkd-pooler.ap-southeast-1.aws.neon.tech"
PG_DATABASE = "Student_attendance"
ENDPOINT_ID = "ep-curly-grass-a163zwkd"

engine_url = (
    f"postgresql+psycopg2://{PG_USER}:{PG_PASSWORD}@{PG_HOST}/{PG_DATABASE}?sslmode=require&options=endpoint%3D{ENDPOINT_ID}"
)

# connection = psycopg2.connect(engine_url)

engine = sqlalchemy.create_engine(engine_url)

In [20]:
tbl_student = pd.read_sql_table("student", engine)
tbl_student.head()

Empty DataFrame
Columns: [id, name, gender]
Index: []

In [21]:
tbl_student.head()

Empty DataFrame
Columns: [id, name, gender]
Index: []

In [55]:
tbl_student = pd.read_sql_table("student", engine)

In [56]:
tbl_student

    No.                  Name Sex nationality
0     1            Chan Panha   M    cambodia
1     2  Chum Ratanakchentria   F    cambodia
2     3           Eang Montra   F    cambodia
3     4          Eung Laimeng   M    cambodia
4     5      Soeun Kongsovann   M    cambodia
5     6           Kril Darith   M    cambodia
6     7  Mao Kolbotr Pisssoth   M    cambodia
7     8            Ny Clinton   M    cambodia
8     9  Phok Keomonnyratanak   M    cambodia
9    10      Rith Sokha Neadh   M    cambodia
10   11              Sat Dona   M    cambodia
11   12         SOPHEAP Neary   M    cambodia
12   13       Srun Chanmonika   F    cambodia
13   15             Tem Lyhor   M    cambodia

In [23]:
tbl_student

   id   name gender
0   1  Borey      M

In [41]:
selected_df = pd.read_sql_query("select count(*) from student", engine)
selected_df

   count
0     28

In [27]:
selected_df.dtypes

id       int64
name    object
dtype: object

In [45]:
stu_data = pd.read_csv("./datasets/01-student-info.csv")
stu_data.head()

   No.                  Name Sex
0    1            Chan Panha   M
1    2  Chum Ratanakchentria   F
2    3           Eang Montra   F
3    4          Eung Laimeng   M
4    5      Soeun Kongsovann   M

In [36]:
stu_data.shape

(14, 3)

In [54]:
stu_data.to_sql("student", engine, if_exists="replace", index=False)

14

In [48]:
stu_data['nationality'] = 'cambodia'

In [49]:
stu_data

    No.                  Name Sex nationality
0     1            Chan Panha   M    cambodia
1     2  Chum Ratanakchentria   F    cambodia
2     3           Eang Montra   F    cambodia
3     4          Eung Laimeng   M    cambodia
4     5      Soeun Kongsovann   M    cambodia
5     6           Kril Darith   M    cambodia
6     7  Mao Kolbotr Pisssoth   M    cambodia
7     8            Ny Clinton   M    cambodia
8     9  Phok Keomonnyratanak   M    cambodia
9    10      Rith Sokha Neadh   M    cambodia
10   11              Sat Dona   M    cambodia
11   12         SOPHEAP Neary   M    cambodia
12   13       Srun Chanmonika   F    cambodia
13   15             Tem Lyhor   M    cambodia

In [59]:
from sqlalchemy import text

with engine.connect() as conn:
    # conn.execute(text('delete from student where "No."= 15'))
    conn.execute(text("delete from student where \"No.\"= 13"))
    conn.commit()

In [60]:
final_df = pd.read_sql_table("student", engine)
final_df

    No.                  Name Sex nationality
0     1            Chan Panha   M    cambodia
1     2  Chum Ratanakchentria   F    cambodia
2     3           Eang Montra   F    cambodia
3     4          Eung Laimeng   M    cambodia
4     5      Soeun Kongsovann   M    cambodia
5     6           Kril Darith   M    cambodia
6     7  Mao Kolbotr Pisssoth   M    cambodia
7     8            Ny Clinton   M    cambodia
8     9  Phok Keomonnyratanak   M    cambodia
9    10      Rith Sokha Neadh   M    cambodia
10   11              Sat Dona   M    cambodia
11   12         SOPHEAP Neary   M    cambodia

In [63]:
ids = [1,2,3]

with engine.connect() as conn:
    conn.execute(text('delete from student where "No." = Any(:student_ids) '), {
        "student_ids": ids
    })
    conn.commit()
final_df = pd.read_sql_table("student", engine)
final_df
final_df

   No.                  Name Sex nationality
0    4          Eung Laimeng   M    cambodia
1    5      Soeun Kongsovann   M    cambodia
2    6           Kril Darith   M    cambodia
3    7  Mao Kolbotr Pisssoth   M    cambodia
4    8            Ny Clinton   M    cambodia
5    9  Phok Keomonnyratanak   M    cambodia
6   10      Rith Sokha Neadh   M    cambodia
7   11              Sat Dona   M    cambodia
8   12         SOPHEAP Neary   M    cambodia